import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ProveedorCarrito from "@/components/cart/CartProvider";
import ProveedorTema from "@/components/theme/ThemeProvider";
import Encabezado from "@/components/Encabezado";
import PieDePagina from "@/components/PieDePagina";
import Script from "next/script";
//

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  viewportFit: "cover",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Script id="viewport-init" strategy="beforeInteractive">
          {`(function(){try{var set=function(){var vh=window.innerHeight/100;var vw=window.innerWidth/100;document.documentElement.style.setProperty('--vh',vh+'px');document.documentElement.style.setProperty('--vw',vw+'px');};set();window.addEventListener('resize',set,{passive:true});window.addEventListener('orientationchange',set,{passive:true});}catch{}})();`}
        </Script>
        <ProveedorTema>
          <ProveedorCarrito>
            <Encabezado />
            <main className="pt-20 pb-6 app-scroll overflow-y-auto pl-[16px] pr-[16px] md:pl-[75px] md:pr-[75px]">{children}</main>
            <PieDePagina />
          </ProveedorCarrito>
        </ProveedorTema>
      </body>
    </html>
  );
}
